openapi: 3.0.0
info:
  title: Malware Analysis API
  version: 1.0.0
paths:
  /analyze:
    post:
      summary: Analyze code snippet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: "def example():\n    print('Hello World')"
      responses:
        '200':
          description: Analysis Report
          content:
            application/json:
              schema:
                type: object
                properties:
                  report:
                    type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
